/**
 * La taxonomía de géneros (tanda 4, §2).
 *
 * ============================================================
 * GENERADO. NO EDITAR A MANO.
 * ============================================================
 *
 * La fuente es GENEROS.md, en la raíz del repo, que es editable y
 * se revisa en un diff. Para cambiar un tag se edita ese archivo y
 * se vuelve a correr:
 *
 *     node scripts/genre-taxonomy-from-md.mjs
 *
 * y después /api/seed-genres, que es lo que lo lleva a la base.
 *
 * Hoy: 34 branches, 719 tags, 50 cross-tags.
 *
 * Archivo puro: sin base de datos, sin React.
 */

export type GenreBranch = {
  /** Código de 3 letras. Es la PK y lo que guardan los perfiles. */
  code: string;
  name: string;
  category: string;
  sortOrder: number;
};

export type GenreTag = {
  slug: string;
  name: string;
  /** Un tag puede repetirse entre branches: es intencional, y por eso
   *  la PK del tag es (slug, branch_code) y no slug solo. */
  branchCode: string;
  sortOrder: number;
};

/** Alias de búsqueda. Se busca por el alias, se muestra la canónica. */
export type GenreAlias = {
  alias: string;
  branchCode: string;
};

export const BRANCHES: GenreBranch[] = [
  { code: "HOU", name: "HOUSE", category: "ELECTRONIC / CLUB", sortOrder: 1 },
  { code: "TEC", name: "TECHNO", category: "ELECTRONIC / CLUB", sortOrder: 2 },
  { code: "TCH", name: "TECH HOUSE", category: "ELECTRONIC / CLUB", sortOrder: 3 },
  { code: "MEL", name: "MELODIC", category: "ELECTRONIC / CLUB", sortOrder: 4 },
  { code: "MIN", name: "MINIMAL", category: "ELECTRONIC / CLUB", sortOrder: 5 },
  { code: "ACI", name: "ACID", category: "ELECTRONIC / CLUB", sortOrder: 6 },
  { code: "GRO", name: "GROOVE", category: "ELECTRONIC / CLUB", sortOrder: 7 },
  { code: "BOU", name: "BOUNCE", category: "ELECTRONIC / CLUB", sortOrder: 8 },
  { code: "IND", name: "INDUSTRIAL", category: "ELECTRONIC / CLUB", sortOrder: 9 },
  { code: "TRI", name: "TRIBAL", category: "ELECTRONIC / CLUB", sortOrder: 10 },
  { code: "TRA", name: "TRANCE", category: "ELECTRONIC / CLUB", sortOrder: 11 },
  { code: "PSY", name: "PSY", category: "ELECTRONIC / CLUB", sortOrder: 12 },
  { code: "HDC", name: "HARDCORE", category: "ELECTRONIC / CLUB", sortOrder: 13 },
  { code: "DNB", name: "DRUM & BASS", category: "ELECTRONIC / CLUB", sortOrder: 14 },
  { code: "GAR", name: "GARAGE", category: "ELECTRONIC / CLUB", sortOrder: 15 },
  { code: "BAS", name: "DUBSTEP / BASS", category: "ELECTRONIC / CLUB", sortOrder: 16 },
  { code: "GUA", name: "GUARACHA", category: "ELECTRONIC / LATIN", sortOrder: 17 },
  { code: "AFR", name: "AFRO", category: "ELECTRONIC / AFRICAN", sortOrder: 18 },
  { code: "AMA", name: "AMAPIANO", category: "ELECTRONIC / AFRICAN", sortOrder: 19 },
  { code: "EDM", name: "EDM / MAINSTAGE", category: "ELECTRONIC / FESTIVAL", sortOrder: 20 },
  { code: "ELC", name: "ELECTRO", category: "ELECTRONIC / CLUB", sortOrder: 21 },
  { code: "DIS", name: "DISCO", category: "DANCE / CLASSICS", sortOrder: 22 },
  { code: "TFB", name: "TRAP / FUTURE BASS", category: "ELECTRONIC / URBAN", sortOrder: 23 },
  { code: "REG", name: "REGGAETÓN", category: "LATIN / URBAN", sortOrder: 24 },
  { code: "HIP", name: "HIP-HOP", category: "URBAN / OPEN FORMAT", sortOrder: 25 },
  { code: "RNB", name: "R&B", category: "URBAN / OPEN FORMAT", sortOrder: 26 },
  { code: "POP", name: "POP / TOP 40", category: "MAINSTREAM / OPEN FORMAT", sortOrder: 27 },
  { code: "AFB", name: "AFROBEATS", category: "AFRICAN / URBAN", sortOrder: 28 },
  { code: "CAR", name: "REGGAE / DANCEHALL", category: "CARIBBEAN / OPEN FORMAT", sortOrder: 29 },
  { code: "BRF", name: "BRAZILIAN FUNK", category: "BRAZIL / URBAN", sortOrder: 30 },
  { code: "LAT", name: "LATIN / TROPICAL", category: "LATIN / OPEN FORMAT", sortOrder: 31 },
  { code: "ROC", name: "ROCK", category: "ROCK / OPEN FORMAT", sortOrder: 32 },
  { code: "FUN", name: "FUNK / SOUL", category: "DANCE / CLASSICS", sortOrder: 33 },
  { code: "CTY", name: "COUNTRY", category: "OPEN FORMAT / US", sortOrder: 34 },
];

export const TAGS: GenreTag[] = [
  { slug: "acid-house", name: "Acid House", branchCode: "HOU", sortOrder: 0 },
  { slug: "funky-house", name: "Funky House", branchCode: "HOU", sortOrder: 1 },
  { slug: "organic-house", name: "Organic House", branchCode: "HOU", sortOrder: 2 },
  { slug: "afro-house", name: "Afro House", branchCode: "HOU", sortOrder: 3 },
  { slug: "future-house", name: "Future House", branchCode: "HOU", sortOrder: 4 },
  { slug: "outsider-house", name: "Outsider House", branchCode: "HOU", sortOrder: 5 },
  { slug: "ambient-house", name: "Ambient House", branchCode: "HOU", sortOrder: 6 },
  { slug: "g-house", name: "G-House", branchCode: "HOU", sortOrder: 7 },
  { slug: "phonk-house", name: "Phonk House", branchCode: "HOU", sortOrder: 8 },
  { slug: "balearic-house-balearic-beat", name: "Balearic House / Balearic Beat", branchCode: "HOU", sortOrder: 9 },
  { slug: "garage-house", name: "Garage House", branchCode: "HOU", sortOrder: 10 },
  { slug: "progressive-house", name: "Progressive House", branchCode: "HOU", sortOrder: 11 },
  { slug: "ballroom-house", name: "Ballroom House", branchCode: "HOU", sortOrder: 12 },
  { slug: "ghetto-house", name: "Ghetto House", branchCode: "HOU", sortOrder: 13 },
  { slug: "slap-house", name: "Slap House", branchCode: "HOU", sortOrder: 14 },
  { slug: "bass-house", name: "Bass House", branchCode: "HOU", sortOrder: 15 },
  { slug: "gospel-house", name: "Gospel House", branchCode: "HOU", sortOrder: 16 },
  { slug: "soulful-house", name: "Soulful House", branchCode: "HOU", sortOrder: 17 },
  { slug: "big-room-house", name: "Big Room House", branchCode: "HOU", sortOrder: 18 },
  { slug: "hard-house", name: "Hard House", branchCode: "HOU", sortOrder: 19 },
  { slug: "speed-house", name: "Speed House", branchCode: "HOU", sortOrder: 20 },
  { slug: "brazilian-bass", name: "Brazilian Bass", branchCode: "HOU", sortOrder: 21 },
  { slug: "hip-house", name: "Hip House", branchCode: "HOU", sortOrder: 22 },
  { slug: "stutter-house", name: "Stutter House", branchCode: "HOU", sortOrder: 23 },
  { slug: "chicago-house", name: "Chicago House", branchCode: "HOU", sortOrder: 24 },
  { slug: "italo-house", name: "Italo House", branchCode: "HOU", sortOrder: 25 },
  { slug: "tech-house", name: "Tech House", branchCode: "HOU", sortOrder: 26 },
  { slug: "classic-house", name: "Classic House", branchCode: "HOU", sortOrder: 27 },
  { slug: "jackin-house", name: "Jackin House", branchCode: "HOU", sortOrder: 28 },
  { slug: "tribal-house", name: "Tribal House", branchCode: "HOU", sortOrder: 29 },
  { slug: "deep-house", name: "Deep House", branchCode: "HOU", sortOrder: 30 },
  { slug: "jazz-house", name: "Jazz House", branchCode: "HOU", sortOrder: 31 },
  { slug: "tropical-house", name: "Tropical House", branchCode: "HOU", sortOrder: 32 },
  { slug: "diva-house", name: "Diva House", branchCode: "HOU", sortOrder: 33 },
  { slug: "latin-house", name: "Latin House", branchCode: "HOU", sortOrder: 34 },
  { slug: "uk-jackin", name: "UK Jackin", branchCode: "HOU", sortOrder: 35 },
  { slug: "electro-house", name: "Electro House", branchCode: "HOU", sortOrder: 36 },
  { slug: "lo-fi-house", name: "Lo-Fi House", branchCode: "HOU", sortOrder: 37 },
  { slug: "vocal-house", name: "Vocal House", branchCode: "HOU", sortOrder: 38 },
  { slug: "euro-house", name: "Euro House", branchCode: "HOU", sortOrder: 39 },
  { slug: "melodic-house", name: "Melodic House", branchCode: "HOU", sortOrder: 40 },
  { slug: "french-house", name: "French House", branchCode: "HOU", sortOrder: 41 },
  { slug: "microhouse", name: "Microhouse", branchCode: "HOU", sortOrder: 42 },
  { slug: "acid-techno", name: "Acid Techno", branchCode: "TEC", sortOrder: 0 },
  { slug: "hypnotic-techno", name: "Hypnotic Techno", branchCode: "TEC", sortOrder: 1 },
  { slug: "dubwise-techno", name: "Dubwise Techno", branchCode: "TEC", sortOrder: 2 },
  { slug: "ambient-techno", name: "Ambient Techno", branchCode: "TEC", sortOrder: 3 },
  { slug: "industrial-techno", name: "Industrial Techno", branchCode: "TEC", sortOrder: 4 },
  { slug: "rave-techno", name: "Rave Techno", branchCode: "TEC", sortOrder: 5 },
  { slug: "birmingham-techno", name: "Birmingham Techno", branchCode: "TEC", sortOrder: 6 },
  { slug: "melodic-techno", name: "Melodic Techno", branchCode: "TEC", sortOrder: 7 },
  { slug: "warehouse-techno", name: "Warehouse Techno", branchCode: "TEC", sortOrder: 8 },
  { slug: "broken-techno", name: "Broken Techno", branchCode: "TEC", sortOrder: 9 },
  { slug: "minimal-techno", name: "Minimal Techno", branchCode: "TEC", sortOrder: 10 },
  { slug: "mental-techno", name: "Mental Techno", branchCode: "TEC", sortOrder: 11 },
  { slug: "deep-techno", name: "Deep Techno", branchCode: "TEC", sortOrder: 12 },
  { slug: "peak-time-techno", name: "Peak Time Techno", branchCode: "TEC", sortOrder: 13 },
  { slug: "freetekno-tekno", name: "Freetekno / Tekno", branchCode: "TEC", sortOrder: 14 },
  { slug: "detroit-techno", name: "Detroit Techno", branchCode: "TEC", sortOrder: 15 },
  { slug: "driving-techno", name: "Driving Techno", branchCode: "TEC", sortOrder: 16 },
  { slug: "hardtek", name: "Hardtek", branchCode: "TEC", sortOrder: 17 },
  { slug: "dub-techno", name: "Dub Techno", branchCode: "TEC", sortOrder: 18 },
  { slug: "psy-techno", name: "Psy-Techno", branchCode: "TEC", sortOrder: 19 },
  { slug: "jungle-techno", name: "Jungle Techno", branchCode: "TEC", sortOrder: 20 },
  { slug: "ebm-techno", name: "EBM Techno", branchCode: "TEC", sortOrder: 21 },
  { slug: "raw-techno", name: "Raw Techno", branchCode: "TEC", sortOrder: 22 },
  { slug: "ghettotech", name: "Ghettotech", branchCode: "TEC", sortOrder: 23 },
  { slug: "hard-techno", name: "Hard Techno", branchCode: "TEC", sortOrder: 24 },
  { slug: "schranz", name: "Schranz", branchCode: "TEC", sortOrder: 25 },
  { slug: "wonky-techno", name: "Wonky Techno", branchCode: "TEC", sortOrder: 26 },
  { slug: "hardgroove-techno", name: "Hardgroove Techno", branchCode: "TEC", sortOrder: 27 },
  { slug: "tribal-techno", name: "Tribal Techno", branchCode: "TEC", sortOrder: 28 },
  { slug: "techno-bass", name: "Techno Bass", branchCode: "TEC", sortOrder: 29 },
  { slug: "classic-tech-house", name: "Classic Tech House", branchCode: "TCH", sortOrder: 0 },
  { slug: "tribal-tech-house", name: "Tribal Tech House", branchCode: "TCH", sortOrder: 1 },
  { slug: "funky-tech-house", name: "Funky Tech House", branchCode: "TCH", sortOrder: 2 },
  { slug: "deep-tech-house", name: "Deep Tech House", branchCode: "TCH", sortOrder: 3 },
  { slug: "afro-tech-house", name: "Afro Tech House", branchCode: "TCH", sortOrder: 4 },
  { slug: "progressive-tech-house", name: "Progressive Tech House", branchCode: "TCH", sortOrder: 5 },
  { slug: "latin-tech", name: "Latin Tech", branchCode: "TCH", sortOrder: 6 },
  { slug: "acid-tech-house", name: "Acid Tech House", branchCode: "TCH", sortOrder: 7 },
  { slug: "vocal-tech-house", name: "Vocal Tech House", branchCode: "TCH", sortOrder: 8 },
  { slug: "minimal-tech-house", name: "Minimal Tech House", branchCode: "TCH", sortOrder: 9 },
  { slug: "melodic-tech-house", name: "Melodic Tech House", branchCode: "TCH", sortOrder: 10 },
  { slug: "underground-tech-house", name: "Underground Tech House", branchCode: "TCH", sortOrder: 11 },
  { slug: "groovy-tech-house", name: "Groovy Tech House", branchCode: "TCH", sortOrder: 12 },
  { slug: "bass-tech-house", name: "Bass Tech House", branchCode: "TCH", sortOrder: 13 },
  { slug: "peak-time-tech-house", name: "Peak-Time Tech House", branchCode: "TCH", sortOrder: 14 },
  { slug: "melodic-house", name: "Melodic House", branchCode: "MEL", sortOrder: 0 },
  { slug: "melodic-dubstep", name: "Melodic Dubstep", branchCode: "MEL", sortOrder: 1 },
  { slug: "organic-melodic", name: "Organic Melodic", branchCode: "MEL", sortOrder: 2 },
  { slug: "melodic-techno", name: "Melodic Techno", branchCode: "MEL", sortOrder: 3 },
  { slug: "melodic-dnb", name: "Melodic DnB", branchCode: "MEL", sortOrder: 4 },
  { slug: "deep-melodic", name: "Deep Melodic", branchCode: "MEL", sortOrder: 5 },
  { slug: "melodic-house-techno", name: "Melodic House & Techno", branchCode: "MEL", sortOrder: 6 },
  { slug: "melodic-hardcore", name: "Melodic Hardcore", branchCode: "MEL", sortOrder: 7 },
  { slug: "dark-melodic", name: "Dark Melodic", branchCode: "MEL", sortOrder: 8 },
  { slug: "progressive-melodic", name: "Progressive Melodic", branchCode: "MEL", sortOrder: 9 },
  { slug: "melodic-funk", name: "Melodic Funk", branchCode: "MEL", sortOrder: 10 },
  { slug: "festival-melodic", name: "Festival Melodic", branchCode: "MEL", sortOrder: 11 },
  { slug: "afro-melodic", name: "Afro Melodic", branchCode: "MEL", sortOrder: 12 },
  { slug: "cinematic-melodic", name: "Cinematic Melodic", branchCode: "MEL", sortOrder: 13 },
  { slug: "melodic-trance", name: "Melodic Trance", branchCode: "MEL", sortOrder: 14 },
  { slug: "vocal-melodic", name: "Vocal Melodic", branchCode: "MEL", sortOrder: 15 },
  { slug: "minimal-house", name: "Minimal House", branchCode: "MIN", sortOrder: 0 },
  { slug: "romanian-minimal-rominimal", name: "Romanian Minimal / Rominimal", branchCode: "MIN", sortOrder: 1 },
  { slug: "dub-minimal", name: "Dub Minimal", branchCode: "MIN", sortOrder: 2 },
  { slug: "minimal-techno", name: "Minimal Techno", branchCode: "MIN", sortOrder: 3 },
  { slug: "minimal-tech-house", name: "Minimal Tech House", branchCode: "MIN", sortOrder: 4 },
  { slug: "micro-techno", name: "Micro Techno", branchCode: "MIN", sortOrder: 5 },
  { slug: "minimal-deep-tech", name: "Minimal / Deep Tech", branchCode: "MIN", sortOrder: 6 },
  { slug: "minimal-dnb", name: "Minimal DnB", branchCode: "MIN", sortOrder: 7 },
  { slug: "click-microhouse", name: "Click / Microhouse", branchCode: "MIN", sortOrder: 8 },
  { slug: "deep-tech", name: "Deep Tech", branchCode: "MIN", sortOrder: 9 },
  { slug: "minimal-dub", name: "Minimal Dub", branchCode: "MIN", sortOrder: 10 },
  { slug: "hypnotic-minimal", name: "Hypnotic Minimal", branchCode: "MIN", sortOrder: 11 },
  { slug: "microhouse", name: "Microhouse", branchCode: "MIN", sortOrder: 12 },
  { slug: "minimal-electro", name: "Minimal Electro", branchCode: "MIN", sortOrder: 13 },
  { slug: "groovy-minimal", name: "Groovy Minimal", branchCode: "MIN", sortOrder: 14 },
  { slug: "acid-house", name: "Acid House", branchCode: "ACI", sortOrder: 0 },
  { slug: "acid-electro", name: "Acid Electro", branchCode: "ACI", sortOrder: 1 },
  { slug: "acid-bass", name: "Acid Bass", branchCode: "ACI", sortOrder: 2 },
  { slug: "acid-techno", name: "Acid Techno", branchCode: "ACI", sortOrder: 3 },
  { slug: "acid-tekno", name: "Acid Tekno", branchCode: "ACI", sortOrder: 4 },
  { slug: "acid-rave", name: "Acid Rave", branchCode: "ACI", sortOrder: 5 },
  { slug: "acid-trance", name: "Acid Trance", branchCode: "ACI", sortOrder: 6 },
  { slug: "acid-hard-techno", name: "Acid Hard Techno", branchCode: "ACI", sortOrder: 7 },
  { slug: "acid-garage", name: "Acid Garage", branchCode: "ACI", sortOrder: 8 },
  { slug: "acidcore", name: "Acidcore", branchCode: "ACI", sortOrder: 9 },
  { slug: "acid-hard-trance", name: "Acid Hard Trance", branchCode: "ACI", sortOrder: 10 },
  { slug: "acid-disco", name: "Acid Disco", branchCode: "ACI", sortOrder: 11 },
  { slug: "acid-breaks", name: "Acid Breaks", branchCode: "ACI", sortOrder: 12 },
  { slug: "acid-psy", name: "Acid Psy", branchCode: "ACI", sortOrder: 13 },
  { slug: "acid-funk", name: "Acid Funk", branchCode: "ACI", sortOrder: 14 },
  { slug: "hardgroove", name: "Hardgroove", branchCode: "GRO", sortOrder: 0 },
  { slug: "percussive-groove", name: "Percussive Groove", branchCode: "GRO", sortOrder: 1 },
  { slug: "hard-groove-house", name: "Hard Groove House", branchCode: "GRO", sortOrder: 2 },
  { slug: "groove-techno", name: "Groove Techno", branchCode: "GRO", sortOrder: 3 },
  { slug: "groove-house", name: "Groove House", branchCode: "GRO", sortOrder: 4 },
  { slug: "rolling-groove", name: "Rolling Groove", branchCode: "GRO", sortOrder: 5 },
  { slug: "groovy-techno", name: "Groovy Techno", branchCode: "GRO", sortOrder: 6 },
  { slug: "funky-groove-house", name: "Funky / Groove House", branchCode: "GRO", sortOrder: 7 },
  { slug: "hypnotic-groove", name: "Hypnotic Groove", branchCode: "GRO", sortOrder: 8 },
  { slug: "funky-techno", name: "Funky Techno", branchCode: "GRO", sortOrder: 9 },
  { slug: "jackin-groove", name: "Jackin Groove", branchCode: "GRO", sortOrder: 10 },
  { slug: "groove-trance", name: "Groove Trance", branchCode: "GRO", sortOrder: 11 },
  { slug: "tribal-groove", name: "Tribal Groove", branchCode: "GRO", sortOrder: 12 },
  { slug: "disco-groove", name: "Disco Groove", branchCode: "GRO", sortOrder: 13 },
  { slug: "latin-groove", name: "Latin Groove", branchCode: "GRO", sortOrder: 14 },
  { slug: "minimal-groove", name: "Minimal Groove", branchCode: "GRO", sortOrder: 15 },
  { slug: "bounce", name: "Bounce", branchCode: "BOU", sortOrder: 0 },
  { slug: "donk", name: "Donk", branchCode: "BOU", sortOrder: 1 },
  { slug: "bouncy-trance", name: "Bouncy Trance", branchCode: "BOU", sortOrder: 2 },
  { slug: "bouncy-techno", name: "Bouncy Techno", branchCode: "BOU", sortOrder: 3 },
  { slug: "scouse-house-bouncy-house", name: "Scouse House / Bouncy House", branchCode: "BOU", sortOrder: 4 },
  { slug: "bouncy-hardcore", name: "Bouncy Hardcore", branchCode: "BOU", sortOrder: 5 },
  { slug: "future-bounce", name: "Future Bounce", branchCode: "BOU", sortOrder: 6 },
  { slug: "bounce-house", name: "Bounce House", branchCode: "BOU", sortOrder: 7 },
  { slug: "latin-bounce", name: "Latin Bounce", branchCode: "BOU", sortOrder: 8 },
  { slug: "melbourne-bounce", name: "Melbourne Bounce", branchCode: "BOU", sortOrder: 9 },
  { slug: "bounce-techno", name: "Bounce Techno", branchCode: "BOU", sortOrder: 10 },
  { slug: "festival-bounce", name: "Festival Bounce", branchCode: "BOU", sortOrder: 11 },
  { slug: "hard-bounce", name: "Hard Bounce", branchCode: "BOU", sortOrder: 12 },
  { slug: "bouncy-hard-techno", name: "Bouncy Hard Techno", branchCode: "BOU", sortOrder: 13 },
  { slug: "industrial-techno", name: "Industrial Techno", branchCode: "IND", sortOrder: 0 },
  { slug: "industrial-trance", name: "Industrial Trance", branchCode: "IND", sortOrder: 1 },
  { slug: "industrial-dnb", name: "Industrial DnB", branchCode: "IND", sortOrder: 2 },
  { slug: "industrial-hardcore", name: "Industrial Hardcore", branchCode: "IND", sortOrder: 3 },
  { slug: "power-noise-rhythmic-noise", name: "Power Noise / Rhythmic Noise", branchCode: "IND", sortOrder: 4 },
  { slug: "industrial-dubstep", name: "Industrial Dubstep", branchCode: "IND", sortOrder: 5 },
  { slug: "industrial-dance", name: "Industrial Dance", branchCode: "IND", sortOrder: 6 },
  { slug: "ebm", name: "EBM", branchCode: "IND", sortOrder: 7 },
  { slug: "industrial-breaks", name: "Industrial Breaks", branchCode: "IND", sortOrder: 8 },
  { slug: "industrial-bass", name: "Industrial Bass", branchCode: "IND", sortOrder: 9 },
  { slug: "dark-electro", name: "Dark Electro", branchCode: "IND", sortOrder: 10 },
  { slug: "industrial-rave", name: "Industrial Rave", branchCode: "IND", sortOrder: 11 },
  { slug: "industrial-electro", name: "Industrial Electro", branchCode: "IND", sortOrder: 12 },
  { slug: "death-industrial", name: "Death Industrial", branchCode: "IND", sortOrder: 13 },
  { slug: "industrial-hard-techno", name: "Industrial Hard Techno", branchCode: "IND", sortOrder: 14 },
  { slug: "tribal-house", name: "Tribal House", branchCode: "TRI", sortOrder: 0 },
  { slug: "guaracha-tribal-guaracha", name: "Guaracha / Tribal Guaracha", branchCode: "TRI", sortOrder: 1 },
  { slug: "tribal-bass", name: "Tribal Bass", branchCode: "TRI", sortOrder: 2 },
  { slug: "tribal-techno", name: "Tribal Techno", branchCode: "TRI", sortOrder: 3 },
  { slug: "percussive-tribal", name: "Percussive Tribal", branchCode: "TRI", sortOrder: 4 },
  { slug: "tribal-groove", name: "Tribal Groove", branchCode: "TRI", sortOrder: 5 },
  { slug: "tribal-tech-house", name: "Tribal Tech House", branchCode: "TRI", sortOrder: 6 },
  { slug: "progressive-tribal", name: "Progressive Tribal", branchCode: "TRI", sortOrder: 7 },
  { slug: "organic-tribal", name: "Organic Tribal", branchCode: "TRI", sortOrder: 8 },
  { slug: "afro-tribal", name: "Afro Tribal", branchCode: "TRI", sortOrder: 9 },
  { slug: "psy-tribal", name: "Psy Tribal", branchCode: "TRI", sortOrder: 10 },
  { slug: "dark-tribal", name: "Dark Tribal", branchCode: "TRI", sortOrder: 11 },
  { slug: "latin-tribal", name: "Latin Tribal", branchCode: "TRI", sortOrder: 12 },
  { slug: "tribal-trance", name: "Tribal Trance", branchCode: "TRI", sortOrder: 13 },
  { slug: "festival-tribal", name: "Festival Tribal", branchCode: "TRI", sortOrder: 14 },
  { slug: "acid-trance", name: "Acid Trance", branchCode: "TRA", sortOrder: 0 },
  { slug: "hypnotic-trance", name: "Hypnotic Trance", branchCode: "TRA", sortOrder: 1 },
  { slug: "goa-trance", name: "Goa Trance", branchCode: "TRA", sortOrder: 2 },
  { slug: "balearic-trance", name: "Balearic Trance", branchCode: "TRA", sortOrder: 3 },
  { slug: "progressive-trance", name: "Progressive Trance", branchCode: "TRA", sortOrder: 4 },
  { slug: "nitzhonot", name: "Nitzhonot", branchCode: "TRA", sortOrder: 5 },
  { slug: "classic-trance", name: "Classic Trance", branchCode: "TRA", sortOrder: 6 },
  { slug: "psytrance", name: "Psytrance", branchCode: "TRA", sortOrder: 7 },
  { slug: "full-on-trance", name: "Full-On Trance", branchCode: "TRA", sortOrder: 8 },
  { slug: "deep-trance", name: "Deep Trance", branchCode: "TRA", sortOrder: 9 },
  { slug: "raw-trance", name: "Raw Trance", branchCode: "TRA", sortOrder: 10 },
  { slug: "future-trance", name: "Future Trance", branchCode: "TRA", sortOrder: 11 },
  { slug: "dream-trance", name: "Dream Trance", branchCode: "TRA", sortOrder: 12 },
  { slug: "tech-trance", name: "Tech Trance", branchCode: "TRA", sortOrder: 13 },
  { slug: "festival-trance", name: "Festival Trance", branchCode: "TRA", sortOrder: 14 },
  { slug: "euro-trance", name: "Euro Trance", branchCode: "TRA", sortOrder: 15 },
  { slug: "uplifting-trance", name: "Uplifting Trance", branchCode: "TRA", sortOrder: 16 },
  { slug: "melodic-trance", name: "Melodic Trance", branchCode: "TRA", sortOrder: 17 },
  { slug: "hard-trance", name: "Hard Trance", branchCode: "TRA", sortOrder: 18 },
  { slug: "vocal-trance", name: "Vocal Trance", branchCode: "TRA", sortOrder: 19 },
  { slug: "psytrance", name: "Psytrance", branchCode: "PSY", sortOrder: 0 },
  { slug: "hi-tech-h-tech-psy", name: "Hi-Tech / H-Tech Psy", branchCode: "PSY", sortOrder: 1 },
  { slug: "psygressive", name: "Psygressive", branchCode: "PSY", sortOrder: 2 },
  { slug: "progressive-psy", name: "Progressive Psy", branchCode: "PSY", sortOrder: 3 },
  { slug: "psy-techno", name: "Psy-Techno", branchCode: "PSY", sortOrder: 4 },
  { slug: "zenonesque", name: "Zenonesque", branchCode: "PSY", sortOrder: 5 },
  { slug: "full-on-psy", name: "Full-On Psy", branchCode: "PSY", sortOrder: 6 },
  { slug: "psybient", name: "Psybient", branchCode: "PSY", sortOrder: 7 },
  { slug: "suomisaundi", name: "Suomisaundi", branchCode: "PSY", sortOrder: 8 },
  { slug: "goa-trance", name: "Goa Trance", branchCode: "PSY", sortOrder: 9 },
  { slug: "psychill", name: "Psychill", branchCode: "PSY", sortOrder: 10 },
  { slug: "night-full-on", name: "Night Full-On", branchCode: "PSY", sortOrder: 11 },
  { slug: "dark-psytrance", name: "Dark Psytrance", branchCode: "PSY", sortOrder: 12 },
  { slug: "psy-dub", name: "Psy Dub", branchCode: "PSY", sortOrder: 13 },
  { slug: "morning-full-on", name: "Morning Full-On", branchCode: "PSY", sortOrder: 14 },
  { slug: "forest-psy", name: "Forest Psy", branchCode: "PSY", sortOrder: 15 },
  { slug: "psy-breaks", name: "Psy Breaks", branchCode: "PSY", sortOrder: 16 },
  { slug: "psychedelic-trance", name: "Psychedelic Trance", branchCode: "PSY", sortOrder: 17 },
  { slug: "psycore", name: "Psycore", branchCode: "PSY", sortOrder: 18 },
  { slug: "psy-bass", name: "Psy Bass", branchCode: "PSY", sortOrder: 19 },
  { slug: "hardcore-techno", name: "Hardcore Techno", branchCode: "HDC", sortOrder: 0 },
  { slug: "extratone", name: "Extratone", branchCode: "HDC", sortOrder: 1 },
  { slug: "bouncy-techno", name: "Bouncy Techno", branchCode: "HDC", sortOrder: 2 },
  { slug: "gabber", name: "Gabber", branchCode: "HDC", sortOrder: 3 },
  { slug: "happy-hardcore", name: "Happy Hardcore", branchCode: "HDC", sortOrder: 4 },
  { slug: "deathchant-hardcore", name: "Deathchant Hardcore", branchCode: "HDC", sortOrder: 5 },
  { slug: "early-hardcore", name: "Early Hardcore", branchCode: "HDC", sortOrder: 6 },
  { slug: "uk-hardcore", name: "UK Hardcore", branchCode: "HDC", sortOrder: 7 },
  { slug: "digital-hardcore", name: "Digital Hardcore", branchCode: "HDC", sortOrder: 8 },
  { slug: "mainstream-hardcore", name: "Mainstream Hardcore", branchCode: "HDC", sortOrder: 9 },
  { slug: "breakbeat-hardcore", name: "Breakbeat Hardcore", branchCode: "HDC", sortOrder: 10 },
  { slug: "crossbreed", name: "Crossbreed", branchCode: "HDC", sortOrder: 11 },
  { slug: "industrial-hardcore", name: "Industrial Hardcore", branchCode: "HDC", sortOrder: 12 },
  { slug: "darkcore", name: "Darkcore", branchCode: "HDC", sortOrder: 13 },
  { slug: "hardtek-tekno", name: "Hardtek / Tekno", branchCode: "HDC", sortOrder: 14 },
  { slug: "frenchcore", name: "Frenchcore", branchCode: "HDC", sortOrder: 15 },
  { slug: "hardcore-breaks", name: "Hardcore Breaks", branchCode: "HDC", sortOrder: 16 },
  { slug: "neo-rave", name: "Neo Rave", branchCode: "HDC", sortOrder: 17 },
  { slug: "uptempo-hardcore", name: "Uptempo Hardcore", branchCode: "HDC", sortOrder: 18 },
  { slug: "acidcore", name: "Acidcore", branchCode: "HDC", sortOrder: 19 },
  { slug: "rawstyle", name: "Rawstyle", branchCode: "HDC", sortOrder: 20 },
  { slug: "terrorcore", name: "Terrorcore", branchCode: "HDC", sortOrder: 21 },
  { slug: "makina", name: "Makina", branchCode: "HDC", sortOrder: 22 },
  { slug: "speedcore", name: "Speedcore", branchCode: "HDC", sortOrder: 23 },
  { slug: "freeform-hardcore", name: "Freeform Hardcore", branchCode: "HDC", sortOrder: 24 },
  { slug: "jungle", name: "Jungle", branchCode: "DNB", sortOrder: 0 },
  { slug: "minimal-dnb", name: "Minimal DnB", branchCode: "DNB", sortOrder: 1 },
  { slug: "sambass", name: "Sambass", branchCode: "DNB", sortOrder: 2 },
  { slug: "liquid-dnb-liquid-funk", name: "Liquid DnB / Liquid Funk", branchCode: "DNB", sortOrder: 3 },
  { slug: "atmospheric-intelligent-dnb", name: "Atmospheric / Intelligent DnB", branchCode: "DNB", sortOrder: 4 },
  { slug: "clownstep", name: "Clownstep", branchCode: "DNB", sortOrder: 5 },
  { slug: "neurofunk", name: "Neurofunk", branchCode: "DNB", sortOrder: 6 },
  { slug: "drumfunk-choppage", name: "Drumfunk / Choppage", branchCode: "DNB", sortOrder: 7 },
  { slug: "crossbreed", name: "Crossbreed", branchCode: "DNB", sortOrder: 8 },
  { slug: "jump-up", name: "Jump Up", branchCode: "DNB", sortOrder: 9 },
  { slug: "halftime-87", name: "Halftime / 87", branchCode: "DNB", sortOrder: 10 },
  { slug: "skullstep", name: "Skullstep", branchCode: "DNB", sortOrder: 11 },
  { slug: "dancefloor-dnb", name: "Dancefloor DnB", branchCode: "DNB", sortOrder: 12 },
  { slug: "autonomic", name: "Autonomic", branchCode: "DNB", sortOrder: 13 },
  { slug: "trancestep", name: "Trancestep", branchCode: "DNB", sortOrder: 14 },
  { slug: "techstep", name: "Techstep", branchCode: "DNB", sortOrder: 15 },
  { slug: "jazzstep", name: "Jazzstep", branchCode: "DNB", sortOrder: 16 },
  { slug: "drumstep", name: "Drumstep", branchCode: "DNB", sortOrder: 17 },
  { slug: "darkstep", name: "Darkstep", branchCode: "DNB", sortOrder: 18 },
  { slug: "ragga-jungle", name: "Ragga Jungle", branchCode: "DNB", sortOrder: 19 },
  { slug: "breakcore", name: "Breakcore", branchCode: "DNB", sortOrder: 20 },
  { slug: "hardstep", name: "Hardstep", branchCode: "DNB", sortOrder: 21 },
  { slug: "darkside-jungle", name: "Darkside Jungle", branchCode: "DNB", sortOrder: 22 },
  { slug: "jungle-tekno", name: "Jungle Tekno", branchCode: "DNB", sortOrder: 23 },
  { slug: "deep-dnb", name: "Deep DnB", branchCode: "DNB", sortOrder: 24 },
  { slug: "rollers", name: "Rollers", branchCode: "DNB", sortOrder: 25 },
  { slug: "uk-garage", name: "UK Garage", branchCode: "GAR", sortOrder: 0 },
  { slug: "garage-house", name: "Garage House", branchCode: "GAR", sortOrder: 1 },
  { slug: "vocal-garage", name: "Vocal Garage", branchCode: "GAR", sortOrder: 2 },
  { slug: "2-step", name: "2-Step", branchCode: "GAR", sortOrder: 3 },
  { slug: "uk-funky", name: "UK Funky", branchCode: "GAR", sortOrder: 4 },
  { slug: "soulful-garage", name: "Soulful Garage", branchCode: "GAR", sortOrder: 5 },
  { slug: "speed-garage", name: "Speed Garage", branchCode: "GAR", sortOrder: 6 },
  { slug: "4x4-garage", name: "4x4 Garage", branchCode: "GAR", sortOrder: 7 },
  { slug: "breakstep", name: "Breakstep", branchCode: "GAR", sortOrder: 8 },
  { slug: "bassline", name: "Bassline", branchCode: "GAR", sortOrder: 9 },
  { slug: "niche-bassline-house", name: "Niche / Bassline House", branchCode: "GAR", sortOrder: 10 },
  { slug: "dubstep-garage", name: "Dubstep Garage", branchCode: "GAR", sortOrder: 11 },
  { slug: "future-garage", name: "Future Garage", branchCode: "GAR", sortOrder: 12 },
  { slug: "grime-influenced-garage", name: "Grime-influenced Garage", branchCode: "GAR", sortOrder: 13 },
  { slug: "ghetto-garage", name: "Ghetto Garage", branchCode: "GAR", sortOrder: 14 },
  { slug: "dark-garage", name: "Dark Garage", branchCode: "GAR", sortOrder: 15 },
  { slug: "deep-garage", name: "Deep Garage", branchCode: "GAR", sortOrder: 16 },
  { slug: "old-school-garage", name: "Old-School Garage", branchCode: "GAR", sortOrder: 17 },
  { slug: "dubstep", name: "Dubstep", branchCode: "BAS", sortOrder: 0 },
  { slug: "post-dubstep", name: "Post-Dubstep", branchCode: "BAS", sortOrder: 1 },
  { slug: "wave", name: "Wave", branchCode: "BAS", sortOrder: 2 },
  { slug: "deep-dubstep", name: "Deep Dubstep", branchCode: "BAS", sortOrder: 3 },
  { slug: "purple-sound", name: "Purple Sound", branchCode: "BAS", sortOrder: 4 },
  { slug: "hardwave", name: "Hardwave", branchCode: "BAS", sortOrder: 5 },
  { slug: "140", name: "140", branchCode: "BAS", sortOrder: 6 },
  { slug: "wonky", name: "Wonky", branchCode: "BAS", sortOrder: 7 },
  { slug: "trapstep", name: "Trapstep", branchCode: "BAS", sortOrder: 8 },
  { slug: "brostep", name: "Brostep", branchCode: "BAS", sortOrder: 9 },
  { slug: "midtempo-bass", name: "Midtempo Bass", branchCode: "BAS", sortOrder: 10 },
  { slug: "drumstep", name: "Drumstep", branchCode: "BAS", sortOrder: 11 },
  { slug: "riddim", name: "Riddim", branchCode: "BAS", sortOrder: 12 },
  { slug: "leftfield-bass", name: "Leftfield Bass", branchCode: "BAS", sortOrder: 13 },
  { slug: "grime", name: "Grime", branchCode: "BAS", sortOrder: 14 },
  { slug: "future-riddim", name: "Future Riddim", branchCode: "BAS", sortOrder: 15 },
  { slug: "experimental-bass", name: "Experimental Bass", branchCode: "BAS", sortOrder: 16 },
  { slug: "juke-footwork", name: "Juke / Footwork", branchCode: "BAS", sortOrder: 17 },
  { slug: "melodic-dubstep", name: "Melodic Dubstep", branchCode: "BAS", sortOrder: 18 },
  { slug: "glitch-hop", name: "Glitch Hop", branchCode: "BAS", sortOrder: 19 },
  { slug: "jersey-club", name: "Jersey Club", branchCode: "BAS", sortOrder: 20 },
  { slug: "deathstep", name: "Deathstep", branchCode: "BAS", sortOrder: 21 },
  { slug: "bass-music", name: "Bass Music", branchCode: "BAS", sortOrder: 22 },
  { slug: "global-club", name: "Global Club", branchCode: "BAS", sortOrder: 23 },
  { slug: "tearout", name: "Tearout", branchCode: "BAS", sortOrder: 24 },
  { slug: "uk-bass", name: "UK Bass", branchCode: "BAS", sortOrder: 25 },
  { slug: "guaracha-edm", name: "Guaracha EDM", branchCode: "GUA", sortOrder: 0 },
  { slug: "guaracha-house", name: "Guaracha House", branchCode: "GUA", sortOrder: 1 },
  { slug: "latin-guaracha", name: "Latin Guaracha", branchCode: "GUA", sortOrder: 2 },
  { slug: "tribal-guaracha", name: "Tribal Guaracha", branchCode: "GUA", sortOrder: 3 },
  { slug: "guaracha-tribal", name: "Guaracha Tribal", branchCode: "GUA", sortOrder: 4 },
  { slug: "festival-guaracha", name: "Festival Guaracha", branchCode: "GUA", sortOrder: 5 },
  { slug: "aleteo", name: "Aleteo", branchCode: "GUA", sortOrder: 6 },
  { slug: "guaracha-rave", name: "Guaracha Rave", branchCode: "GUA", sortOrder: 7 },
  { slug: "colombian-tribal", name: "Colombian Tribal", branchCode: "GUA", sortOrder: 8 },
  { slug: "zapateo", name: "Zapateo", branchCode: "GUA", sortOrder: 9 },
  { slug: "hard-guaracha", name: "Hard Guaracha", branchCode: "GUA", sortOrder: 10 },
  { slug: "circuit-tribal-guaracha", name: "Circuit / Tribal Guaracha", branchCode: "GUA", sortOrder: 11 },
  { slug: "guaracha-tech", name: "Guaracha Tech", branchCode: "GUA", sortOrder: 12 },
  { slug: "psy-guaracha", name: "Psy Guaracha", branchCode: "GUA", sortOrder: 13 },
  { slug: "afro-house", name: "Afro House", branchCode: "AFR", sortOrder: 0 },
  { slug: "kwaito", name: "Kwaito", branchCode: "AFR", sortOrder: 1 },
  { slug: "afro-funk", name: "Afro Funk", branchCode: "AFR", sortOrder: 2 },
  { slug: "afro-tech", name: "Afro Tech", branchCode: "AFR", sortOrder: 3 },
  { slug: "afro-deep", name: "Afro Deep", branchCode: "AFR", sortOrder: 4 },
  { slug: "organic-afro", name: "Organic Afro", branchCode: "AFR", sortOrder: 5 },
  { slug: "afro-techno", name: "Afro Techno", branchCode: "AFR", sortOrder: 6 },
  { slug: "afro-progressive", name: "Afro Progressive", branchCode: "AFR", sortOrder: 7 },
  { slug: "ancestral-house", name: "Ancestral House", branchCode: "AFR", sortOrder: 8 },
  { slug: "afro-melodic", name: "Afro Melodic", branchCode: "AFR", sortOrder: 9 },
  { slug: "afro-tribal", name: "Afro Tribal", branchCode: "AFR", sortOrder: 10 },
  { slug: "afro-soulful", name: "Afro Soulful", branchCode: "AFR", sortOrder: 11 },
  { slug: "afro-latin-house", name: "Afro / Latin House", branchCode: "AFR", sortOrder: 12 },
  { slug: "afro-electronic", name: "Afro Electronic", branchCode: "AFR", sortOrder: 13 },
  { slug: "afro-latin", name: "Afro Latin", branchCode: "AFR", sortOrder: 14 },
  { slug: "3-step", name: "3-Step", branchCode: "AFR", sortOrder: 15 },
  { slug: "afro-bass", name: "Afro Bass", branchCode: "AFR", sortOrder: 16 },
  { slug: "gqom", name: "Gqom", branchCode: "AFR", sortOrder: 17 },
  { slug: "afro-disco", name: "Afro Disco", branchCode: "AFR", sortOrder: 18 },
  { slug: "amapiano", name: "Amapiano", branchCode: "AMA", sortOrder: 0 },
  { slug: "deep-amapiano", name: "Deep Amapiano", branchCode: "AMA", sortOrder: 1 },
  { slug: "piano-hub-mainstream-amapiano", name: "Piano Hub / Mainstream Amapiano", branchCode: "AMA", sortOrder: 2 },
  { slug: "private-school-amapiano", name: "Private School Amapiano", branchCode: "AMA", sortOrder: 3 },
  { slug: "jazz-amapiano", name: "Jazz Amapiano", branchCode: "AMA", sortOrder: 4 },
  { slug: "afro-amapiano", name: "Afro Amapiano", branchCode: "AMA", sortOrder: 5 },
  { slug: "log-drum-amapiano", name: "Log Drum Amapiano", branchCode: "AMA", sortOrder: 6 },
  { slug: "sgija", name: "Sgija", branchCode: "AMA", sortOrder: 7 },
  { slug: "3-step", name: "3-Step", branchCode: "AMA", sortOrder: 8 },
  { slug: "vocal-amapiano", name: "Vocal Amapiano", branchCode: "AMA", sortOrder: 9 },
  { slug: "quantum-sound", name: "Quantum Sound", branchCode: "AMA", sortOrder: 10 },
  { slug: "tech-amapiano", name: "Tech Amapiano", branchCode: "AMA", sortOrder: 11 },
  { slug: "soulful-amapiano", name: "Soulful Amapiano", branchCode: "AMA", sortOrder: 12 },
  { slug: "bacardi-house", name: "Bacardi House", branchCode: "AMA", sortOrder: 13 },
  { slug: "gqom-influenced-amapiano", name: "Gqom-influenced Amapiano", branchCode: "AMA", sortOrder: 14 },
  { slug: "big-room", name: "Big Room", branchCode: "EDM", sortOrder: 0 },
  { slug: "festival-house", name: "Festival House", branchCode: "EDM", sortOrder: 1 },
  { slug: "festival-trance", name: "Festival Trance", branchCode: "EDM", sortOrder: 2 },
  { slug: "mainstage", name: "Mainstage", branchCode: "EDM", sortOrder: 3 },
  { slug: "festival-techno", name: "Festival Techno", branchCode: "EDM", sortOrder: 4 },
  { slug: "bass-house", name: "Bass House", branchCode: "EDM", sortOrder: 5 },
  { slug: "electro-house", name: "Electro House", branchCode: "EDM", sortOrder: 6 },
  { slug: "hands-up", name: "Hands Up", branchCode: "EDM", sortOrder: 7 },
  { slug: "slap-house", name: "Slap House", branchCode: "EDM", sortOrder: 8 },
  { slug: "festival-progressive-house", name: "Festival Progressive House", branchCode: "EDM", sortOrder: 9 },
  { slug: "commercial-dance", name: "Commercial Dance", branchCode: "EDM", sortOrder: 10 },
  { slug: "future-bounce", name: "Future Bounce", branchCode: "EDM", sortOrder: 11 },
  { slug: "future-house", name: "Future House", branchCode: "EDM", sortOrder: 12 },
  { slug: "dance-pop", name: "Dance / Pop", branchCode: "EDM", sortOrder: 13 },
  { slug: "electro-pop", name: "Electro Pop", branchCode: "EDM", sortOrder: 14 },
  { slug: "future-rave", name: "Future Rave", branchCode: "EDM", sortOrder: 15 },
  { slug: "progressive-edm", name: "Progressive EDM", branchCode: "EDM", sortOrder: 16 },
  { slug: "stadium-edm", name: "Stadium EDM", branchCode: "EDM", sortOrder: 17 },
  { slug: "big-room-techno", name: "Big Room Techno", branchCode: "EDM", sortOrder: 18 },
  { slug: "big-room-trance", name: "Big Room Trance", branchCode: "EDM", sortOrder: 19 },
  { slug: "classic-electro", name: "Classic Electro", branchCode: "ELC", sortOrder: 0 },
  { slug: "electro-bass", name: "Electro Bass", branchCode: "ELC", sortOrder: 1 },
  { slug: "freestyle-electro", name: "Freestyle Electro", branchCode: "ELC", sortOrder: 2 },
  { slug: "detroit-electro", name: "Detroit Electro", branchCode: "ELC", sortOrder: 3 },
  { slug: "electro-breaks", name: "Electro Breaks", branchCode: "ELC", sortOrder: 4 },
  { slug: "ghettotech", name: "Ghettotech", branchCode: "ELC", sortOrder: 5 },
  { slug: "modern-electro", name: "Modern Electro", branchCode: "ELC", sortOrder: 6 },
  { slug: "dark-electro", name: "Dark Electro", branchCode: "ELC", sortOrder: 7 },
  { slug: "breakdance-electro", name: "Breakdance Electro", branchCode: "ELC", sortOrder: 8 },
  { slug: "electro-funk", name: "Electro-Funk", branchCode: "ELC", sortOrder: 9 },
  { slug: "minimal-electro", name: "Minimal Electro", branchCode: "ELC", sortOrder: 10 },
  { slug: "electropop", name: "Electropop", branchCode: "ELC", sortOrder: 11 },
  { slug: "electroclash", name: "Electroclash", branchCode: "ELC", sortOrder: 12 },
  { slug: "acid-electro", name: "Acid Electro", branchCode: "ELC", sortOrder: 13 },
  { slug: "electro-industrial", name: "Electro-industrial", branchCode: "ELC", sortOrder: 14 },
  { slug: "electro-house", name: "Electro House", branchCode: "ELC", sortOrder: 15 },
  { slug: "nu-electro", name: "Nu Electro", branchCode: "ELC", sortOrder: 16 },
  { slug: "electro-techno", name: "Electro Techno", branchCode: "ELC", sortOrder: 17 },
  { slug: "miami-bass", name: "Miami Bass", branchCode: "ELC", sortOrder: 18 },
  { slug: "classic-disco", name: "Classic Disco", branchCode: "DIS", sortOrder: 0 },
  { slug: "boogie", name: "Boogie", branchCode: "DIS", sortOrder: 1 },
  { slug: "future-funk", name: "Future Funk", branchCode: "DIS", sortOrder: 2 },
  { slug: "nu-disco", name: "Nu-Disco", branchCode: "DIS", sortOrder: 3 },
  { slug: "disco-funk", name: "Disco Funk", branchCode: "DIS", sortOrder: 4 },
  { slug: "balearic-disco", name: "Balearic Disco", branchCode: "DIS", sortOrder: 5 },
  { slug: "italo-disco", name: "Italo Disco", branchCode: "DIS", sortOrder: 6 },
  { slug: "disco-soul", name: "Disco Soul", branchCode: "DIS", sortOrder: 7 },
  { slug: "dark-disco", name: "Dark Disco", branchCode: "DIS", sortOrder: 8 },
  { slug: "eurodisco", name: "Eurodisco", branchCode: "DIS", sortOrder: 9 },
  { slug: "latin-disco", name: "Latin Disco", branchCode: "DIS", sortOrder: 10 },
  { slug: "indie-dance-disco", name: "Indie Dance / Disco", branchCode: "DIS", sortOrder: 11 },
  { slug: "space-disco", name: "Space Disco", branchCode: "DIS", sortOrder: 12 },
  { slug: "disco-house", name: "Disco House", branchCode: "DIS", sortOrder: 13 },
  { slug: "afro-disco", name: "Afro Disco", branchCode: "DIS", sortOrder: 14 },
  { slug: "cosmic-disco", name: "Cosmic Disco", branchCode: "DIS", sortOrder: 15 },
  { slug: "french-house-filter-disco", name: "French House / Filter Disco", branchCode: "DIS", sortOrder: 16 },
  { slug: "electro-disco", name: "Electro Disco", branchCode: "DIS", sortOrder: 17 },
  { slug: "hi-nrg", name: "Hi-NRG", branchCode: "DIS", sortOrder: 18 },
  { slug: "disco-pop", name: "Disco Pop", branchCode: "DIS", sortOrder: 19 },
  { slug: "psychedelic-disco", name: "Psychedelic Disco", branchCode: "DIS", sortOrder: 20 },
  { slug: "post-disco", name: "Post-Disco", branchCode: "DIS", sortOrder: 21 },
  { slug: "disco-rap", name: "Disco Rap", branchCode: "DIS", sortOrder: 22 },
  { slug: "disco-edits-re-edits", name: "Disco Edits / Re-Edits", branchCode: "DIS", sortOrder: 23 },
  { slug: "edm-trap", name: "EDM Trap", branchCode: "TFB", sortOrder: 0 },
  { slug: "kawaii-future-bass", name: "Kawaii Future Bass", branchCode: "TFB", sortOrder: 1 },
  { slug: "bass-trap", name: "Bass Trap", branchCode: "TFB", sortOrder: 2 },
  { slug: "festival-trap", name: "Festival Trap", branchCode: "TFB", sortOrder: 3 },
  { slug: "chill-trap", name: "Chill Trap", branchCode: "TFB", sortOrder: 4 },
  { slug: "latin-trap", name: "Latin Trap", branchCode: "TFB", sortOrder: 5 },
  { slug: "hard-trap", name: "Hard Trap", branchCode: "TFB", sortOrder: 6 },
  { slug: "wave", name: "Wave", branchCode: "TFB", sortOrder: 7 },
  { slug: "afro-trap", name: "Afro Trap", branchCode: "TFB", sortOrder: 8 },
  { slug: "hybrid-trap", name: "Hybrid Trap", branchCode: "TFB", sortOrder: 9 },
  { slug: "hardwave", name: "Hardwave", branchCode: "TFB", sortOrder: 10 },
  { slug: "phonk-drift-phonk", name: "Phonk / Drift Phonk", branchCode: "TFB", sortOrder: 11 },
  { slug: "trapstep", name: "Trapstep", branchCode: "TFB", sortOrder: 12 },
  { slug: "future-trap", name: "Future Trap", branchCode: "TFB", sortOrder: 13 },
  { slug: "jersey-influenced-trap", name: "Jersey-influenced Trap", branchCode: "TFB", sortOrder: 14 },
  { slug: "future-bass", name: "Future Bass", branchCode: "TFB", sortOrder: 15 },
  { slug: "melodic-trap", name: "Melodic Trap", branchCode: "TFB", sortOrder: 16 },
  { slug: "glitch-trap", name: "Glitch Trap", branchCode: "TFB", sortOrder: 17 },
  { slug: "old-school-reggaeton", name: "Old-School Reggaetón", branchCode: "REG", sortOrder: 0 },
  { slug: "reggaeton-alternativo", name: "Reggaetón Alternativo", branchCode: "REG", sortOrder: 1 },
  { slug: "latin-urban", name: "Latin Urban", branchCode: "REG", sortOrder: 2 },
  { slug: "classic-reggaeton", name: "Classic Reggaetón", branchCode: "REG", sortOrder: 3 },
  { slug: "reggaeton-underground", name: "Reggaetón Underground", branchCode: "REG", sortOrder: 4 },
  { slug: "dembow", name: "Dembow", branchCode: "REG", sortOrder: 5 },
  { slug: "modern-reggaeton", name: "Modern Reggaetón", branchCode: "REG", sortOrder: 6 },
  { slug: "reggaeton-mexicano", name: "Reggaetón Mexicano", branchCode: "REG", sortOrder: 7 },
  { slug: "malianteo", name: "Malianteo", branchCode: "REG", sortOrder: 8 },
  { slug: "reggaeton-pop", name: "Reggaetón Pop", branchCode: "REG", sortOrder: 9 },
  { slug: "colombian-reggaeton", name: "Colombian Reggaetón", branchCode: "REG", sortOrder: 10 },
  { slug: "playero", name: "Playero", branchCode: "REG", sortOrder: 11 },
  { slug: "pop-urbano", name: "Pop Urbano", branchCode: "REG", sortOrder: 12 },
  { slug: "puerto-rican-reggaeton", name: "Puerto Rican Reggaetón", branchCode: "REG", sortOrder: 13 },
  { slug: "sandungueo", name: "Sandungueo", branchCode: "REG", sortOrder: 14 },
  { slug: "perreo", name: "Perreo", branchCode: "REG", sortOrder: 15 },
  { slug: "reggaeton-house", name: "Reggaetón House", branchCode: "REG", sortOrder: 16 },
  { slug: "reggaeton-2000s", name: "Reggaetón 2000s", branchCode: "REG", sortOrder: 17 },
  { slug: "perreo-intenso", name: "Perreo Intenso", branchCode: "REG", sortOrder: 18 },
  { slug: "reggaeton-tech", name: "Reggaetón Tech", branchCode: "REG", sortOrder: 19 },
  { slug: "reggaeton-2010s", name: "Reggaetón 2010s", branchCode: "REG", sortOrder: 20 },
  { slug: "neoperreo", name: "Neoperreo", branchCode: "REG", sortOrder: 21 },
  { slug: "reggaeton-edm", name: "Reggaetón EDM", branchCode: "REG", sortOrder: 22 },
  { slug: "reggaeton-2020s", name: "Reggaetón 2020s", branchCode: "REG", sortOrder: 23 },
  { slug: "romantic-reggaeton", name: "Romantic Reggaetón", branchCode: "REG", sortOrder: 24 },
  { slug: "reggaeton-trap", name: "Reggaetón Trap", branchCode: "REG", sortOrder: 25 },
  { slug: "east-coast", name: "East Coast", branchCode: "HIP", sortOrder: 0 },
  { slug: "abstract-hip-hop", name: "Abstract Hip-Hop", branchCode: "HIP", sortOrder: 1 },
  { slug: "g-funk", name: "G-Funk", branchCode: "HIP", sortOrder: 2 },
  { slug: "west-coast", name: "West Coast", branchCode: "HIP", sortOrder: 3 },
  { slug: "trap", name: "Trap", branchCode: "HIP", sortOrder: 4 },
  { slug: "crunk", name: "Crunk", branchCode: "HIP", sortOrder: 5 },
  { slug: "southern-hip-hop", name: "Southern Hip-Hop", branchCode: "HIP", sortOrder: 6 },
  { slug: "drill", name: "Drill", branchCode: "HIP", sortOrder: 7 },
  { slug: "miami-bass", name: "Miami Bass", branchCode: "HIP", sortOrder: 8 },
  { slug: "global-hip-hop", name: "Global Hip-Hop", branchCode: "HIP", sortOrder: 9 },
  { slug: "jersey-drill", name: "Jersey Drill", branchCode: "HIP", sortOrder: 10 },
  { slug: "phonk", name: "Phonk", branchCode: "HIP", sortOrder: 11 },
  { slug: "boom-bap", name: "Boom Bap", branchCode: "HIP", sortOrder: 12 },
  { slug: "latin-hip-hop", name: "Latin Hip-Hop", branchCode: "HIP", sortOrder: 13 },
  { slug: "emo-rap", name: "Emo Rap", branchCode: "HIP", sortOrder: 14 },
  { slug: "old-school-hip-hop", name: "Old School Hip-Hop", branchCode: "HIP", sortOrder: 15 },
  { slug: "uk-hip-hop", name: "UK Hip-Hop", branchCode: "HIP", sortOrder: 16 },
  { slug: "party-rap", name: "Party Rap", branchCode: "HIP", sortOrder: 17 },
  { slug: "golden-age-hip-hop", name: "Golden Age Hip-Hop", branchCode: "HIP", sortOrder: 18 },
  { slug: "grime", name: "Grime", branchCode: "HIP", sortOrder: 19 },
  { slug: "commercial-hip-hop", name: "Commercial Hip-Hop", branchCode: "HIP", sortOrder: 20 },
  { slug: "gangsta-rap", name: "Gangsta Rap", branchCode: "HIP", sortOrder: 21 },
  { slug: "cloud-rap", name: "Cloud Rap", branchCode: "HIP", sortOrder: 22 },
  { slug: "underground-hip-hop", name: "Underground Hip-Hop", branchCode: "HIP", sortOrder: 23 },
  { slug: "conscious-hip-hop", name: "Conscious Hip-Hop", branchCode: "HIP", sortOrder: 24 },
  { slug: "lo-fi-hip-hop", name: "Lo-Fi Hip-Hop", branchCode: "HIP", sortOrder: 25 },
  { slug: "alternative-hip-hop", name: "Alternative Hip-Hop", branchCode: "HIP", sortOrder: 26 },
  { slug: "jazz-rap", name: "Jazz Rap", branchCode: "HIP", sortOrder: 27 },
  { slug: "contemporary-r-b", name: "Contemporary R&B", branchCode: "RNB", sortOrder: 0 },
  { slug: "soul", name: "Soul", branchCode: "RNB", sortOrder: 1 },
  { slug: "trap-soul", name: "Trap Soul", branchCode: "RNB", sortOrder: 2 },
  { slug: "classic-r-b", name: "Classic R&B", branchCode: "RNB", sortOrder: 3 },
  { slug: "funk", name: "Funk", branchCode: "RNB", sortOrder: 4 },
  { slug: "electronic-r-b", name: "Electronic R&B", branchCode: "RNB", sortOrder: 5 },
  { slug: "90s-r-b", name: "90s R&B", branchCode: "RNB", sortOrder: 6 },
  { slug: "quiet-storm", name: "Quiet Storm", branchCode: "RNB", sortOrder: 7 },
  { slug: "dance-r-b", name: "Dance R&B", branchCode: "RNB", sortOrder: 8 },
  { slug: "2000s-r-b", name: "2000s R&B", branchCode: "RNB", sortOrder: 9 },
  { slug: "new-jack-swing", name: "New Jack Swing", branchCode: "RNB", sortOrder: 10 },
  { slug: "pop-r-b", name: "Pop R&B", branchCode: "RNB", sortOrder: 11 },
  { slug: "alternative-r-b", name: "Alternative R&B", branchCode: "RNB", sortOrder: 12 },
  { slug: "hip-hop-soul", name: "Hip-Hop Soul", branchCode: "RNB", sortOrder: 13 },
  { slug: "slow-jams", name: "Slow Jams", branchCode: "RNB", sortOrder: 14 },
  { slug: "progressive-r-b", name: "Progressive R&B", branchCode: "RNB", sortOrder: 15 },
  { slug: "afro-r-b", name: "Afro R&B", branchCode: "RNB", sortOrder: 16 },
  { slug: "future-r-b", name: "Future R&B", branchCode: "RNB", sortOrder: 17 },
  { slug: "neo-soul", name: "Neo Soul", branchCode: "RNB", sortOrder: 18 },
  { slug: "latin-r-b", name: "Latin R&B", branchCode: "RNB", sortOrder: 19 },
  { slug: "pop", name: "Pop", branchCode: "POP", sortOrder: 0 },
  { slug: "j-pop", name: "J-Pop", branchCode: "POP", sortOrder: 1 },
  { slug: "urban-pop", name: "Urban Pop", branchCode: "POP", sortOrder: 2 },
  { slug: "top-40", name: "Top 40", branchCode: "POP", sortOrder: 3 },
  { slug: "afropop", name: "Afropop", branchCode: "POP", sortOrder: 4 },
  { slug: "throwback-pop", name: "Throwback Pop", branchCode: "POP", sortOrder: 5 },
  { slug: "dance-pop", name: "Dance Pop", branchCode: "POP", sortOrder: 6 },
  { slug: "country-pop", name: "Country Pop", branchCode: "POP", sortOrder: 7 },
  { slug: "80s-pop", name: "80s Pop", branchCode: "POP", sortOrder: 8 },
  { slug: "electropop", name: "Electropop", branchCode: "POP", sortOrder: 9 },
  { slug: "disco-pop", name: "Disco Pop", branchCode: "POP", sortOrder: 10 },
  { slug: "90s-pop", name: "90s Pop", branchCode: "POP", sortOrder: 11 },
  { slug: "synth-pop", name: "Synth-Pop", branchCode: "POP", sortOrder: 12 },
  { slug: "hyperpop", name: "Hyperpop", branchCode: "POP", sortOrder: 13 },
  { slug: "2000s-pop", name: "2000s Pop", branchCode: "POP", sortOrder: 14 },
  { slug: "indie-pop", name: "Indie Pop", branchCode: "POP", sortOrder: 15 },
  { slug: "teen-pop", name: "Teen Pop", branchCode: "POP", sortOrder: 16 },
  { slug: "2010s-pop", name: "2010s Pop", branchCode: "POP", sortOrder: 17 },
  { slug: "pop-rock", name: "Pop Rock", branchCode: "POP", sortOrder: 18 },
  { slug: "adult-contemporary", name: "Adult Contemporary", branchCode: "POP", sortOrder: 19 },
  { slug: "2020s-pop", name: "2020s Pop", branchCode: "POP", sortOrder: 20 },
  { slug: "pop-rap", name: "Pop Rap", branchCode: "POP", sortOrder: 21 },
  { slug: "power-pop", name: "Power Pop", branchCode: "POP", sortOrder: 22 },
  { slug: "party-pop", name: "Party Pop", branchCode: "POP", sortOrder: 23 },
  { slug: "latin-pop", name: "Latin Pop", branchCode: "POP", sortOrder: 24 },
  { slug: "euro-pop", name: "Euro Pop", branchCode: "POP", sortOrder: 25 },
  { slug: "clean-pop", name: "Clean Pop", branchCode: "POP", sortOrder: 26 },
  { slug: "k-pop", name: "K-Pop", branchCode: "POP", sortOrder: 27 },
  { slug: "tropical-pop", name: "Tropical Pop", branchCode: "POP", sortOrder: 28 },
  { slug: "afrobeats", name: "Afrobeats", branchCode: "AFB", sortOrder: 0 },
  { slug: "amapiano-crossover", name: "Amapiano Crossover", branchCode: "AFB", sortOrder: 1 },
  { slug: "ghanaian-afrobeats", name: "Ghanaian Afrobeats", branchCode: "AFB", sortOrder: 2 },
  { slug: "afropop", name: "Afropop", branchCode: "AFB", sortOrder: 3 },
  { slug: "afro-trap", name: "Afro Trap", branchCode: "AFB", sortOrder: 4 },
  { slug: "highlife-influenced-afrobeats", name: "Highlife-influenced Afrobeats", branchCode: "AFB", sortOrder: 5 },
  { slug: "afro-r-b", name: "Afro R&B", branchCode: "AFB", sortOrder: 6 },
  { slug: "afro-drill", name: "Afro Drill", branchCode: "AFB", sortOrder: 7 },
  { slug: "afro-soul", name: "Afro Soul", branchCode: "AFB", sortOrder: 8 },
  { slug: "afro-fusion", name: "Afro-Fusion", branchCode: "AFB", sortOrder: 9 },
  { slug: "afro-hip-hop", name: "Afro Hip-Hop", branchCode: "AFB", sortOrder: 10 },
  { slug: "afro-gospel", name: "Afro Gospel", branchCode: "AFB", sortOrder: 11 },
  { slug: "afro-swing", name: "Afro Swing", branchCode: "AFB", sortOrder: 12 },
  { slug: "afro-dancehall", name: "Afro Dancehall", branchCode: "AFB", sortOrder: 13 },
  { slug: "afro-urban", name: "Afro Urban", branchCode: "AFB", sortOrder: 14 },
  { slug: "afro-bashment", name: "Afro Bashment", branchCode: "AFB", sortOrder: 15 },
  { slug: "afro-pop", name: "Afro Pop", branchCode: "AFB", sortOrder: 16 },
  { slug: "alte", name: "Alte", branchCode: "AFB", sortOrder: 17 },
  { slug: "naija-pop", name: "Naija Pop", branchCode: "AFB", sortOrder: 18 },
  { slug: "reggae", name: "Reggae", branchCode: "CAR", sortOrder: 0 },
  { slug: "digital-dancehall", name: "Digital Dancehall", branchCode: "CAR", sortOrder: 1 },
  { slug: "reggae-pop", name: "Reggae Pop", branchCode: "CAR", sortOrder: 2 },
  { slug: "roots-reggae", name: "Roots Reggae", branchCode: "CAR", sortOrder: 3 },
  { slug: "lovers-rock", name: "Lovers Rock", branchCode: "CAR", sortOrder: 4 },
  { slug: "dub-poetry", name: "Dub Poetry", branchCode: "CAR", sortOrder: 5 },
  { slug: "dub", name: "Dub", branchCode: "CAR", sortOrder: 6 },
  { slug: "soca", name: "Soca", branchCode: "CAR", sortOrder: 7 },
  { slug: "trap-dancehall", name: "Trap Dancehall", branchCode: "CAR", sortOrder: 8 },
  { slug: "dancehall", name: "Dancehall", branchCode: "CAR", sortOrder: 9 },
  { slug: "calypso", name: "Calypso", branchCode: "CAR", sortOrder: 10 },
  { slug: "afro-dancehall", name: "Afro Dancehall", branchCode: "CAR", sortOrder: 11 },
  { slug: "old-school-dancehall", name: "Old-School Dancehall", branchCode: "CAR", sortOrder: 12 },
  { slug: "ska", name: "Ska", branchCode: "CAR", sortOrder: 13 },
  { slug: "latin-dancehall", name: "Latin Dancehall", branchCode: "CAR", sortOrder: 14 },
  { slug: "modern-dancehall", name: "Modern Dancehall", branchCode: "CAR", sortOrder: 15 },
  { slug: "rocksteady", name: "Rocksteady", branchCode: "CAR", sortOrder: 16 },
  { slug: "caribbean-bass", name: "Caribbean Bass", branchCode: "CAR", sortOrder: 17 },
  { slug: "ragga", name: "Ragga", branchCode: "CAR", sortOrder: 18 },
  { slug: "reggae-fusion", name: "Reggae Fusion", branchCode: "CAR", sortOrder: 19 },
  { slug: "ragga-jungle", name: "Ragga Jungle", branchCode: "CAR", sortOrder: 20 },
  { slug: "funk-carioca", name: "Funk Carioca", branchCode: "BRF", sortOrder: 0 },
  { slug: "funk-ostentacao", name: "Funk Ostentação", branchCode: "BRF", sortOrder: 1 },
  { slug: "funk-rave", name: "Funk Rave", branchCode: "BRF", sortOrder: 2 },
  { slug: "baile-funk", name: "Baile Funk", branchCode: "BRF", sortOrder: 3 },
  { slug: "funk-melody", name: "Funk Melody", branchCode: "BRF", sortOrder: 4 },
  { slug: "brazilian-bass-funk", name: "Brazilian Bass Funk", branchCode: "BRF", sortOrder: 5 },
  { slug: "mandelao-funk", name: "Mandelao Funk", branchCode: "BRF", sortOrder: 6 },
  { slug: "rasteirinha", name: "Rasteirinha", branchCode: "BRF", sortOrder: 7 },
  { slug: "phonk-brasileiro", name: "Phonk Brasileiro", branchCode: "BRF", sortOrder: 8 },
  { slug: "bh-funk", name: "BH Funk", branchCode: "BRF", sortOrder: 9 },
  { slug: "brega-funk", name: "Brega Funk", branchCode: "BRF", sortOrder: 10 },
  { slug: "mega-funk", name: "Mega Funk", branchCode: "BRF", sortOrder: 11 },
  { slug: "melodic-funk", name: "Melodic Funk", branchCode: "BRF", sortOrder: 12 },
  { slug: "funk-150-bpm", name: "Funk 150 BPM", branchCode: "BRF", sortOrder: 13 },
  { slug: "funk-mtg", name: "Funk MTG", branchCode: "BRF", sortOrder: 14 },
  { slug: "eletrofunk", name: "Eletrofunk", branchCode: "BRF", sortOrder: 15 },
  { slug: "funk-170-bpm", name: "Funk 170 BPM", branchCode: "BRF", sortOrder: 16 },
  { slug: "funk-automotivo", name: "Funk Automotivo", branchCode: "BRF", sortOrder: 17 },
  { slug: "funk-proibidao", name: "Funk Proibidão", branchCode: "BRF", sortOrder: 18 },
  { slug: "salsa", name: "Salsa", branchCode: "LAT", sortOrder: 0 },
  { slug: "champeta", name: "Champeta", branchCode: "LAT", sortOrder: 1 },
  { slug: "musica-popular-colombiana", name: "Música Popular Colombiana", branchCode: "LAT", sortOrder: 2 },
  { slug: "salsa-dura", name: "Salsa Dura", branchCode: "LAT", sortOrder: 3 },
  { slug: "soca", name: "Soca", branchCode: "LAT", sortOrder: 4 },
  { slug: "tropical", name: "Tropical", branchCode: "LAT", sortOrder: 5 },
  { slug: "salsa-romantica", name: "Salsa Romántica", branchCode: "LAT", sortOrder: 6 },
  { slug: "mambo", name: "Mambo", branchCode: "LAT", sortOrder: 7 },
  { slug: "tropical-urbano", name: "Tropical Urbano", branchCode: "LAT", sortOrder: 8 },
  { slug: "merengue", name: "Merengue", branchCode: "LAT", sortOrder: 9 },
  { slug: "latin-dance", name: "Latin Dance", branchCode: "LAT", sortOrder: 10 },
  { slug: "electrocumbia", name: "Electrocumbia", branchCode: "LAT", sortOrder: 11 },
  { slug: "bachata", name: "Bachata", branchCode: "LAT", sortOrder: 12 },
  { slug: "latin-pop", name: "Latin Pop", branchCode: "LAT", sortOrder: 13 },
  { slug: "moombahton", name: "Moombahton", branchCode: "LAT", sortOrder: 14 },
  { slug: "cumbia", name: "Cumbia", branchCode: "LAT", sortOrder: 15 },
  { slug: "latin-house", name: "Latin House", branchCode: "LAT", sortOrder: 16 },
  { slug: "salsa-choke", name: "Salsa Choke", branchCode: "LAT", sortOrder: 17 },
  { slug: "cumbia-sonidera", name: "Cumbia Sonidera", branchCode: "LAT", sortOrder: 18 },
  { slug: "latin-hip-hop", name: "Latin Hip-Hop", branchCode: "LAT", sortOrder: 19 },
  { slug: "merenhouse", name: "Merenhouse", branchCode: "LAT", sortOrder: 20 },
  { slug: "cumbia-villera", name: "Cumbia Villera", branchCode: "LAT", sortOrder: 21 },
  { slug: "dembow", name: "Dembow", branchCode: "LAT", sortOrder: 22 },
  { slug: "latin-disco", name: "Latin Disco", branchCode: "LAT", sortOrder: 23 },
  { slug: "vallenato", name: "Vallenato", branchCode: "LAT", sortOrder: 24 },
  { slug: "regional-mexican", name: "Regional Mexican", branchCode: "LAT", sortOrder: 25 },
  { slug: "classic-rock", name: "Classic Rock", branchCode: "ROC", sortOrder: 0 },
  { slug: "post-punk", name: "Post-Punk", branchCode: "ROC", sortOrder: 1 },
  { slug: "latin-rock", name: "Latin Rock", branchCode: "ROC", sortOrder: 2 },
  { slug: "alternative-rock", name: "Alternative Rock", branchCode: "ROC", sortOrder: 3 },
  { slug: "new-wave", name: "New Wave", branchCode: "ROC", sortOrder: 4 },
  { slug: "dance-rock", name: "Dance-Rock", branchCode: "ROC", sortOrder: 5 },
  { slug: "indie-rock", name: "Indie Rock", branchCode: "ROC", sortOrder: 6 },
  { slug: "grunge", name: "Grunge", branchCode: "ROC", sortOrder: 7 },
  { slug: "electronic-rock", name: "Electronic Rock", branchCode: "ROC", sortOrder: 8 },
  { slug: "hard-rock", name: "Hard Rock", branchCode: "ROC", sortOrder: 9 },
  { slug: "metal", name: "Metal", branchCode: "ROC", sortOrder: 10 },
  { slug: "industrial-rock", name: "Industrial Rock", branchCode: "ROC", sortOrder: 11 },
  { slug: "garage-rock", name: "Garage Rock", branchCode: "ROC", sortOrder: 12 },
  { slug: "heavy-metal", name: "Heavy Metal", branchCode: "ROC", sortOrder: 13 },
  { slug: "gothic-rock", name: "Gothic Rock", branchCode: "ROC", sortOrder: 14 },
  { slug: "psychedelic-rock", name: "Psychedelic Rock", branchCode: "ROC", sortOrder: 15 },
  { slug: "glam-rock", name: "Glam Rock", branchCode: "ROC", sortOrder: 16 },
  { slug: "emo", name: "Emo", branchCode: "ROC", sortOrder: 17 },
  { slug: "progressive-rock", name: "Progressive Rock", branchCode: "ROC", sortOrder: 18 },
  { slug: "glam-metal", name: "Glam Metal", branchCode: "ROC", sortOrder: 19 },
  { slug: "post-rock", name: "Post-Rock", branchCode: "ROC", sortOrder: 20 },
  { slug: "pop-rock", name: "Pop Rock", branchCode: "ROC", sortOrder: 21 },
  { slug: "britpop", name: "Britpop", branchCode: "ROC", sortOrder: 22 },
  { slug: "shoegaze", name: "Shoegaze", branchCode: "ROC", sortOrder: 23 },
  { slug: "punk-rock", name: "Punk Rock", branchCode: "ROC", sortOrder: 24 },
  { slug: "surf-rock", name: "Surf Rock", branchCode: "ROC", sortOrder: 25 },
  { slug: "rock-en-espanol", name: "Rock en Español", branchCode: "ROC", sortOrder: 26 },
  { slug: "pop-punk", name: "Pop Punk", branchCode: "ROC", sortOrder: 27 },
  { slug: "southern-rock", name: "Southern Rock", branchCode: "ROC", sortOrder: 28 },
  { slug: "yacht-rock", name: "Yacht Rock", branchCode: "ROC", sortOrder: 29 },
  { slug: "funk", name: "Funk", branchCode: "FUN", sortOrder: 0 },
  { slug: "latin-funk", name: "Latin Funk", branchCode: "FUN", sortOrder: 1 },
  { slug: "southern-soul", name: "Southern Soul", branchCode: "FUN", sortOrder: 2 },
  { slug: "classic-funk", name: "Classic Funk", branchCode: "FUN", sortOrder: 3 },
  { slug: "disco-funk", name: "Disco Funk", branchCode: "FUN", sortOrder: 4 },
  { slug: "philly-soul", name: "Philly Soul", branchCode: "FUN", sortOrder: 5 },
  { slug: "p-funk", name: "P-Funk", branchCode: "FUN", sortOrder: 6 },
  { slug: "jazz-funk", name: "Jazz-Funk", branchCode: "FUN", sortOrder: 7 },
  { slug: "neo-soul", name: "Neo Soul", branchCode: "FUN", sortOrder: 8 },
  { slug: "deep-funk", name: "Deep Funk", branchCode: "FUN", sortOrder: 9 },
  { slug: "future-funk", name: "Future Funk", branchCode: "FUN", sortOrder: 10 },
  { slug: "psychedelic-soul", name: "Psychedelic Soul", branchCode: "FUN", sortOrder: 11 },
  { slug: "electro-funk", name: "Electro-Funk", branchCode: "FUN", sortOrder: 12 },
  { slug: "soul", name: "Soul", branchCode: "FUN", sortOrder: 13 },
  { slug: "motown", name: "Motown", branchCode: "FUN", sortOrder: 14 },
  { slug: "boogie", name: "Boogie", branchCode: "FUN", sortOrder: 15 },
  { slug: "classic-soul", name: "Classic Soul", branchCode: "FUN", sortOrder: 16 },
  { slug: "rare-groove", name: "Rare Groove", branchCode: "FUN", sortOrder: 17 },
  { slug: "g-funk", name: "G-Funk", branchCode: "FUN", sortOrder: 18 },
  { slug: "deep-soul", name: "Deep Soul", branchCode: "FUN", sortOrder: 19 },
  { slug: "funk-soul-edits", name: "Funk / Soul Edits", branchCode: "FUN", sortOrder: 20 },
  { slug: "afro-funk", name: "Afro-Funk", branchCode: "FUN", sortOrder: 21 },
  { slug: "northern-soul", name: "Northern Soul", branchCode: "FUN", sortOrder: 22 },
  { slug: "country", name: "Country", branchCode: "CTY", sortOrder: 0 },
  { slug: "outlaw-country", name: "Outlaw Country", branchCode: "CTY", sortOrder: 1 },
  { slug: "country-rap-hick-hop", name: "Country Rap / Hick-Hop", branchCode: "CTY", sortOrder: 2 },
  { slug: "classic-country", name: "Classic Country", branchCode: "CTY", sortOrder: 3 },
  { slug: "americana", name: "Americana", branchCode: "CTY", sortOrder: 4 },
  { slug: "country-edm-yeedm", name: "Country EDM / YEEDM", branchCode: "CTY", sortOrder: 5 },
  { slug: "contemporary-country", name: "Contemporary Country", branchCode: "CTY", sortOrder: 6 },
  { slug: "bluegrass", name: "Bluegrass", branchCode: "CTY", sortOrder: 7 },
  { slug: "line-dance-country", name: "Line Dance Country", branchCode: "CTY", sortOrder: 8 },
  { slug: "country-pop", name: "Country Pop", branchCode: "CTY", sortOrder: 9 },
  { slug: "bro-country", name: "Bro-Country", branchCode: "CTY", sortOrder: 10 },
  { slug: "90s-country", name: "90s Country", branchCode: "CTY", sortOrder: 11 },
  { slug: "country-rock", name: "Country Rock", branchCode: "CTY", sortOrder: 12 },
  { slug: "neo-traditional-country", name: "Neo-Traditional Country", branchCode: "CTY", sortOrder: 13 },
  { slug: "2000s-country", name: "2000s Country", branchCode: "CTY", sortOrder: 14 },
  { slug: "country-dance", name: "Country Dance", branchCode: "CTY", sortOrder: 15 },
  { slug: "alt-country", name: "Alt-Country", branchCode: "CTY", sortOrder: 16 },
  { slug: "modern-country", name: "Modern Country", branchCode: "CTY", sortOrder: 17 },
  { slug: "honky-tonk", name: "Honky-Tonk", branchCode: "CTY", sortOrder: 18 },
  { slug: "western-swing", name: "Western Swing", branchCode: "CTY", sortOrder: 19 },
];

/**
 * Los alias que la regla del documento nombra: DnB = Drum & Bass,
 * UKG = Garage, Guaracha = Aleteo/Zapateo. Son varias filas porque
 * cada forma de escribirlo es un alias distinto al mismo branch.
 */
export const ALIASES: GenreAlias[] = [
  { alias: "DnB", branchCode: "DNB" },
  { alias: "Drum and Bass", branchCode: "DNB" },
  { alias: "D&B", branchCode: "DNB" },
  { alias: "UKG", branchCode: "GAR" },
  { alias: "Aleteo", branchCode: "GUA" },
  { alias: "Zapateo", branchCode: "GUA" },
];

export type CrossTagKind = "dj_type" | "era" | "contexto" | "formato" | "energia";

export type CrossTag = {
  slug: string;
  name: string;
  kind: CrossTagKind;
  sortOrder: number;
};

/** Era, contexto, formato, energía y tipo de DJ. Van fuera del género
 *  y no se infiere un branch padre desde ninguno de ellos. */
export const CROSS_TAGS: CrossTag[] = [
  { slug: "specialist", name: "Specialist", kind: "dj_type", sortOrder: 0 },
  { slug: "open-format-crossover", name: "Open Format / Crossover", kind: "dj_type", sortOrder: 1 },
  { slug: "multi-genre", name: "Multi-Genre", kind: "dj_type", sortOrder: 2 },
  { slug: "selector-curator", name: "Selector / Curator", kind: "dj_type", sortOrder: 3 },
  { slug: "turntablist", name: "Turntablist", kind: "dj_type", sortOrder: 4 },
  { slug: "live-hybrid-dj", name: "Live / Hybrid DJ", kind: "dj_type", sortOrder: 5 },
  { slug: "70s", name: "70s", kind: "era", sortOrder: 100 },
  { slug: "80s", name: "80s", kind: "era", sortOrder: 101 },
  { slug: "90s", name: "90s", kind: "era", sortOrder: 102 },
  { slug: "2000s", name: "2000s", kind: "era", sortOrder: 103 },
  { slug: "2010s", name: "2010s", kind: "era", sortOrder: 104 },
  { slug: "2020s", name: "2020s", kind: "era", sortOrder: 105 },
  { slug: "old-school", name: "Old School", kind: "era", sortOrder: 106 },
  { slug: "classic", name: "Classic", kind: "era", sortOrder: 107 },
  { slug: "current-new-music", name: "Current / New Music", kind: "era", sortOrder: 108 },
  { slug: "throwbacks", name: "Throwbacks", kind: "era", sortOrder: 109 },
  { slug: "club", name: "Club", kind: "contexto", sortOrder: 200 },
  { slug: "underground", name: "Underground", kind: "contexto", sortOrder: 201 },
  { slug: "warehouse", name: "Warehouse", kind: "contexto", sortOrder: 202 },
  { slug: "festival", name: "Festival", kind: "contexto", sortOrder: 203 },
  { slug: "rooftop", name: "Rooftop", kind: "contexto", sortOrder: 204 },
  { slug: "open-air", name: "Open Air", kind: "contexto", sortOrder: 205 },
  { slug: "afterhours", name: "Afterhours", kind: "contexto", sortOrder: 206 },
  { slug: "house-party", name: "House Party", kind: "contexto", sortOrder: 207 },
  { slug: "wedding-private-event", name: "Wedding / Private Event", kind: "contexto", sortOrder: 208 },
  { slug: "corporate", name: "Corporate", kind: "contexto", sortOrder: 209 },
  { slug: "radio-broadcast", name: "Radio / Broadcast", kind: "contexto", sortOrder: 210 },
  { slug: "vinyl", name: "Vinyl", kind: "formato", sortOrder: 300 },
  { slug: "digital", name: "Digital", kind: "formato", sortOrder: 301 },
  { slug: "cdj", name: "CDJ", kind: "formato", sortOrder: 302 },
  { slug: "controller", name: "Controller", kind: "formato", sortOrder: 303 },
  { slug: "live-remixing", name: "Live Remixing", kind: "formato", sortOrder: 304 },
  { slug: "live-pa-hybrid", name: "Live PA Hybrid", kind: "formato", sortOrder: 305 },
  { slug: "scratching", name: "Scratching", kind: "formato", sortOrder: 306 },
  { slug: "open-format-mixing", name: "Open Format Mixing", kind: "formato", sortOrder: 307 },
  { slug: "extended-sets", name: "Extended Sets", kind: "formato", sortOrder: 308 },
  { slug: "b2b", name: "B2B", kind: "formato", sortOrder: 309 },
  { slug: "warm-up", name: "Warm-Up", kind: "energia", sortOrder: 400 },
  { slug: "peak-time", name: "Peak-Time", kind: "energia", sortOrder: 401 },
  { slug: "closing", name: "Closing", kind: "energia", sortOrder: 402 },
  { slug: "deep", name: "Deep", kind: "energia", sortOrder: 403 },
  { slug: "dark", name: "Dark", kind: "energia", sortOrder: 404 },
  { slug: "hypnotic", name: "Hypnotic", kind: "energia", sortOrder: 405 },
  { slug: "groovy", name: "Groovy", kind: "energia", sortOrder: 406 },
  { slug: "melodic", name: "Melodic", kind: "energia", sortOrder: 407 },
  { slug: "hard", name: "Hard", kind: "energia", sortOrder: 408 },
  { slug: "fast", name: "Fast", kind: "energia", sortOrder: 409 },
  { slug: "emotional", name: "Emotional", kind: "energia", sortOrder: 410 },
  { slug: "commercial", name: "Commercial", kind: "energia", sortOrder: 411 },
  { slug: "experimental", name: "Experimental", kind: "energia", sortOrder: 412 },
];

/**
 * Reglas del documento que el write path tiene que hacer cumplir. No
 * son CHECK de Postgres porque cuentan filas hermanas.
 *
 * El documento dice "Allow 3-8 genre Tags per DJ; rank the first 3 as
 * Primary Tags", así que el mínimo es 3 y no 1.
 */
export const GENRE_RULES = {
  /** Un solo branch primario. Esto SÍ es un índice único parcial. */
  primaryBranches: 1,
  maxSecondaryBranches: 3,
  minTags: 3,
  maxTags: 8,
  /** Los tres primeros tags son los primarios, por orden. */
  primaryTags: 3,
} as const;

/** Nombre a slug: sin acentos, sin barras, sin espacios. */
export function slugify(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
